#cloud-config
prefer_fqdn_over_hostname: false
hostname: NAS
locale: de_DE.UTF-8
timezone: Europe/Berlin
users:
  - name: root
    homedir: /root
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII76gjWeMy9xfu7EAD2guCp4QoP9UGQtPEbQgsFLjXSE
runcmd:
  - set -e
  - set -x

  - systemctl enable podman.socket --now
  - systemctl enable podman-restart --now

  - export HOME=/root
  - cd $HOME
  - echo "alias pc='podman compose' >> .bashrc"

  - export REPO_NAME=nas
  - git clone "https://github.com/Alex1s/$REPO_NAME.git"
  - cd "$REPO_NAME"
  - ./init.sh
package_reboot_if_required: true
package_update: true
package_upgrade: false
packages:
  - podman
  - git-core